import requests

url = "https://secure5.store.apple.com/shop/mdp/api/echo"

payload = {
    "deliveryVersion": "1.0",
    "postTime": 1717171873974,
    "events": [
        {
            "app": "com.apple.www.Store",
            "eventType": "custom_event",
            "postTime": 1717171871534,
            "host": "secure5.store.apple.com",
            "pageHostname": "secure5.store.apple.com",
            "pagePathname": "/shop/signIn/account",
            "pageUrl": "https://secure5.store.apple.com/shop/signIn/account?<query>",
            "pageViewId": "e08214cf-4909-4e5e-b396-8fecc92dfb9b",
            "sessionStartTS": 1717171871481,
            "exists": True,
            "passed": True,
            "algorithm": "RSA-OAEP",
            "encryptTime": 31,
            "decryptTime": 20.399999976158142,
            "asDc": "ucp2",
            "audit": {
                "echo": {"version": ["3.18.1"]},
                "react": {"version": ["18.2.0"]},
            },
            "cookies": ["as_dc", "as_sfa", "geo"],
            "pageId": "AOS: Checkout Sign In",
            "pageShopPath": "/signIn/account?ssi=1AAABj89rYOEg4-281Jy2q_T4lYuqdh_plE6j6MI6siODeWtQ6lqsPdAAAAAzaHR0cHM6Ly9zZWN1cmU1LnN0b3JlLmFwcGxlLmNvbS9zaG9wL2FjY291bnQvaG9tZXx8AAIBJeHD8tM2zuNWWp_pEBjk36NdS0Z__gVPaH6k7tM4kLo",
            "pixelRatio": 1,
            "pluginCount": 5,
            "pxro": "null",
            "rsNames": ["rs-web"],
            "screenHeight": 1080,
            "screenWidth": 1920,
            "scripts": 12,
            "styles": 6,
            "validPageUrl": True,
            "windowInnerHeight": 924,
            "windowInnerWidth": 1125,
            "windowOrientation": 0,
            "windowOuterHeight": 1032,
            "windowOuterWidth": 1920,
            "environment": "",
            "format": "common",
            "sf": "us",
            "segment": "Consumer",
            "locale": "en-us",
            "referer": "",
            "node": "transaction/sign_in/account",
            "pageResource": "rs-account-4",
            "feature": "unified-signin",
            "targetEnabled": "false",
            "tags": [],
        },
        {
            "app": "com.apple.www.Store",
            "eventType": "pageview",
            "postTime": 1717171873973,
            "host": "secure5.store.apple.com",
            "pageHostname": "secure5.store.apple.com",
            "pagePathname": "/shop/signIn/account",
            "pageUrl": "https://secure5.store.apple.com/shop/signIn/account?<query>",
            "pageViewId": "e08214cf-4909-4e5e-b396-8fecc92dfb9b",
            "sessionStartTS": 1717171871481,
            "triggeredBy": "load",
            "name": "https://secure5.store.apple.com/shop/signIn/account?ssi=1AAABj89rYOEg4-281Jy2q_T4lYuqdh_plE6j6MI6siODeWtQ6lqsPdAAAAAzaHR0cHM6Ly9zZWN1cmU1LnN0b3JlLmFwcGxlLmNvbS9zaG9wL2FjY291bnQvaG9tZXx8AAIBJeHD8tM2zuNWWp_pEBjk36NdS0Z__gVPaH6k7tM4kLo",
            "entryType": "navigation",
            "startTime": 0,
            "duration": 4157,
            "initiatorType": "navigation",
            "deliveryType": "",
            "nextHopProtocol": "h2",
            "renderBlockingStatus": "non-blocking",
            "workerStart": 0,
            "redirectStart": 0,
            "redirectEnd": 0,
            "fetchStart": 1411.9000000357628,
            "domainLookupStart": 1411.9000000357628,
            "domainLookupEnd": 1411.9000000357628,
            "connectStart": 1411.9000000357628,
            "secureConnectionStart": 1411.9000000357628,
            "connectEnd": 1411.9000000357628,
            "requestStart": 1413.800000011921,
            "responseStart": 1656.800000011921,
            "firstInterimResponseStart": 0,
            "responseEnd": 1872.6000000238419,
            "transferSize": 26329,
            "encodedBodySize": 26029,
            "decodedBodySize": 100395,
            "responseStatus": 200,
            "serverTiming": [],
            "unloadEventStart": 0,
            "unloadEventEnd": 0,
            "domInteractive": 2169.900000035763,
            "domContentLoadedEventStart": 2272.7000000476837,
            "domContentLoadedEventEnd": 2279.800000011921,
            "domComplete": 4155.900000035763,
            "loadEventStart": 4156.400000035763,
            "loadEventEnd": 4157,
            "type": "navigate",
            "redirectCount": 0,
            "activationStart": 0,
            "criticalCHRestart": 0,
            "notRestoredReasons": None,
            "NavigationTimingLevel": 2,
            "networkDownlink": 10,
            "networkEffectiveType": "4g",
            "networkRtt": 50,
            "imageCountOnLoad": 0,
            "support": {"subtleCrypto": True},
            "referer": "",
            "asDc": "ucp2",
            "audit": {
                "echo": {"version": ["3.18.1"]},
                "react": {"version": ["18.2.0"]},
            },
            "cookies": ["as_dc", "as_sfa", "geo", "pxro", "s_fid", "s_cc", "s_vi"],
            "pageId": "AOS: Checkout Sign In",
            "pageShopPath": "/signIn/account?ssi=1AAABj89rYOEg4-281Jy2q_T4lYuqdh_plE6j6MI6siODeWtQ6lqsPdAAAAAzaHR0cHM6Ly9zZWN1cmU1LnN0b3JlLmFwcGxlLmNvbS9zaG9wL2FjY291bnQvaG9tZXx8AAIBJeHD8tM2zuNWWp_pEBjk36NdS0Z__gVPaH6k7tM4kLo",
            "pixelRatio": 1,
            "pluginCount": 5,
            "pxro": 1,
            "rsNames": ["rs-web"],
            "screenHeight": 1080,
            "screenWidth": 1920,
            "scripts": 12,
            "styles": 6,
            "validPageUrl": True,
            "windowInnerHeight": 924,
            "windowInnerWidth": 1125,
            "windowOrientation": 0,
            "windowOuterHeight": 1032,
            "windowOuterWidth": 1920,
            "environment": "",
            "format": "common",
            "sf": "us",
            "segment": "Consumer",
            "locale": "en-us",
            "node": "transaction/sign_in/account",
            "pageResource": "rs-account-4",
            "feature": "unified-signin",
            "targetEnabled": "false",
            "tags": [],
        },
        {
            "app": "com.apple.www.Store",
            "eventType": "paint",
            "postTime": 1717171871527,
            "host": "secure5.store.apple.com",
            "pageHostname": "secure5.store.apple.com",
            "pagePathname": "/shop/signIn/account",
            "pageUrl": "https://secure5.store.apple.com/shop/signIn/account?<query>",
            "pageViewId": "e08214cf-4909-4e5e-b396-8fecc92dfb9b",
            "sessionStartTS": 1717171871481,
            "name": "first-paint",
            "entryType": "paint",
            "startTime": 2180.800000011921,
            "duration": 0,
            "asDc": "ucp2",
            "audit": {
                "echo": {"version": ["3.18.1"]},
                "react": {"version": ["18.2.0"]},
            },
            "cookies": ["as_dc", "as_sfa", "geo"],
            "pageId": "AOS: Checkout Sign In",
            "pageShopPath": "/signIn/account?ssi=1AAABj89rYOEg4-281Jy2q_T4lYuqdh_plE6j6MI6siODeWtQ6lqsPdAAAAAzaHR0cHM6Ly9zZWN1cmU1LnN0b3JlLmFwcGxlLmNvbS9zaG9wL2FjY291bnQvaG9tZXx8AAIBJeHD8tM2zuNWWp_pEBjk36NdS0Z__gVPaH6k7tM4kLo",
            "pixelRatio": 1,
            "pluginCount": 5,
            "pxro": "null",
            "rsNames": ["rs-web"],
            "screenHeight": 1080,
            "screenWidth": 1920,
            "scripts": 12,
            "styles": 6,
            "validPageUrl": True,
            "windowInnerHeight": 924,
            "windowInnerWidth": 1125,
            "windowOrientation": 0,
            "windowOuterHeight": 1032,
            "windowOuterWidth": 1920,
            "environment": "",
            "format": "common",
            "sf": "us",
            "segment": "Consumer",
            "locale": "en-us",
            "referer": "",
            "node": "transaction/sign_in/account",
            "pageResource": "rs-account-4",
            "feature": "unified-signin",
            "targetEnabled": "false",
            "tags": [],
        },
        {
            "app": "com.apple.www.Store",
            "eventType": "paint",
            "postTime": 1717171871528,
            "host": "secure5.store.apple.com",
            "pageHostname": "secure5.store.apple.com",
            "pagePathname": "/shop/signIn/account",
            "pageUrl": "https://secure5.store.apple.com/shop/signIn/account?<query>",
            "pageViewId": "e08214cf-4909-4e5e-b396-8fecc92dfb9b",
            "sessionStartTS": 1717171871481,
            "name": "first-contentful-paint",
            "entryType": "paint",
            "startTime": 2180.800000011921,
            "duration": 0,
            "asDc": "ucp2",
            "audit": {
                "echo": {"version": ["3.18.1"]},
                "react": {"version": ["18.2.0"]},
            },
            "cookies": ["as_dc", "as_sfa", "geo"],
            "pageId": "AOS: Checkout Sign In",
            "pageShopPath": "/signIn/account?ssi=1AAABj89rYOEg4-281Jy2q_T4lYuqdh_plE6j6MI6siODeWtQ6lqsPdAAAAAzaHR0cHM6Ly9zZWN1cmU1LnN0b3JlLmFwcGxlLmNvbS9zaG9wL2FjY291bnQvaG9tZXx8AAIBJeHD8tM2zuNWWp_pEBjk36NdS0Z__gVPaH6k7tM4kLo",
            "pixelRatio": 1,
            "pluginCount": 5,
            "pxro": "null",
            "rsNames": ["rs-web"],
            "screenHeight": 1080,
            "screenWidth": 1920,
            "scripts": 12,
            "styles": 6,
            "validPageUrl": True,
            "windowInnerHeight": 924,
            "windowInnerWidth": 1125,
            "windowOrientation": 0,
            "windowOuterHeight": 1032,
            "windowOuterWidth": 1920,
            "environment": "",
            "format": "common",
            "sf": "us",
            "segment": "Consumer",
            "locale": "en-us",
            "referer": "",
            "node": "transaction/sign_in/account",
            "pageResource": "rs-account-4",
            "feature": "unified-signin",
            "targetEnabled": "false",
            "tags": [],
        },
    ],
}
headers = {
    "accept": "*/*",
    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
    "cache-control": "no-cache",
    "content-type": "application/json",
    "dnt": "1",
    "origin": "https://secure5.store.apple.com",
    "pragma": "no-cache",
    "priority": "u=1, i",
    "referer": "https://secure5.store.apple.com/shop/signIn/account?ssi=1AAABj89rYOEg4-281Jy2q_T4lYuqdh_plE6j6MI6siODeWtQ6lqsPdAAAAAzaHR0cHM6Ly9zZWN1cmU1LnN0b3JlLmFwcGxlLmNvbS9zaG9wL2FjY291bnQvaG9tZXx8AAIBJeHD8tM2zuNWWp_pEBjk36NdS0Z__gVPaH6k7tM4kLo",
    "sec-ch-ua-mobile": "?0",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0",
    "Cookie": "dssid2=98c33257-5ed0-4cb8-a247-4cfa39e64c77; dssf=1; as_pcts=IdDnGY1Cy1OROoQuVPi9MNSH_9O:DD0y23as-N9DToCsHMlUMQRqlohzxeXFqU3ly4DIzAw:zX2QYpO81jE3_S0j1+RWPNlWH5Jj5CvuAPCYVKIb24PGNC-FY:HHJ06cqX+SO-a3LB:rzDfQv95sryCWEb1bUWC08UJaMkox2:X+MFhWxaD; as_dc=ucp2; as_sfa=Mnx1c3x1c3x8ZW5fVVN8Y29uc3VtZXJ8aW50ZXJuZXR8MHwwfDE; geo=CN; pxro=1; s_fid=6DE32246D0424CBA-0DF0789FD0F39C37; s_cc=true; s_vi=[CS]v1|332CFB50F8E15079-400017842BFBAA6F[CE]; dslang=US-EN; site=USA",
}

response = requests.request("POST", url, json=payload, headers=headers)

print(response.headers)
